[build-system]
requires = [ "poetry-core>=1.0.0",]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "poetry_unpinned"
version = "0.1.0"
description = ""
authors = [ "Your Name <you@example.com>",]

[tool.poetry.dependencies]
python = "^3.9"
Django = "*"
django-bootstrap5 = "*"
requests = "*"

[tool.poetry.dev-dependencies]

[tool.poetry.group.deploy]
optional = true

[tool.poetry.group.deploy.dependencies]
django-simple-deploy = "*"
gunicorn = "*"
psycopg2-binary = "*"
dj-database-url = "*"
whitenoise = "*"
